// server.js
const express = require("express");
const cors = require("cors");
const path = require("path");
const fs = require("fs/promises");

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ---------- AUTO-GENERATE FILES ON FIRST RUN ----------
(async () => {
  try {
    const publicPath = path.join(__dirname, "public");
    const versionsPath = path.join(__dirname, "versions.json");

    // Create /public if not exists
    await fs.mkdir(publicPath, { recursive: true });

    // Create index.html if missing
    const indexHtml = `
<!DOCTYPE html>
<html>
<head>
  <title>App Version Explorer</title>
  <style>
    body { font-family: Arial; padding: 30px; }
    .app { margin-bottom: 20px; padding: 10px; border: 1px solid #aaa; border-radius: 5px; }
  </style>
</head>
<body>
  <h1>App Version Explorer</h1>
  <p>This file was auto-generated by server.js</p>
  <div id="list"></div>

  <script>
    fetch('/api/versions')
      .then(r => r.json())
      .then(res => {
        const container = document.getElementById('list');
        for (const app in res.data) {
          const div = document.createElement('div');
          div.className = 'app';
          div.innerHTML = '<strong>' + app + '</strong><br>Versions: ' + res.data[app].versions.join(', ');
          container.appendChild(div);
        }
      });
  </script>
</body>
</html>
    `;

    try {
      await fs.access(path.join(publicPath, "index.html"));
    } catch {
      await fs.writeFile(path.join(publicPath, "index.html"), indexHtml);
      console.log("Auto-created: public/index.html");
    }

    // Create versions.json if missing
    const sampleJson = {
      "MyApp": {
        "versions": ["1.0.0", "1.1.0", "2.0.0"]
      },
      "SuperCalc": {
        "versions": ["0.9", "1.0", "1.3"]
      }
    };

    try {
      await fs.access(versionsPath);
    } catch {
      await fs.writeFile(
        versionsPath,
        JSON.stringify(sampleJson, null, 2)
      );
      console.log("Auto-created: versions.json");
    }

  } catch (err) {
    console.error("Setup error:", err);
  }
})();

// ---------- API ROUTES ----------
app.get("/api/versions", async (req, res) => {
  try {
    const filePath = path.join(__dirname, "versions.json");
    const data = JSON.parse(await fs.readFile(filePath, "utf-8"));
    res.json({ success: true, data });
  } catch (err) {
    res.status(500).json({ success: false, message: "Could not read versions.json" });
  }
});

// ---------- STATIC FRONTEND ----------
app.use(express.static(path.join(__dirname, "public")));

// ---------- SPA FALLBACK ----------
app.get("*", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

// ---------- START SERVER ----------
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
